jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
      - docker/push:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME 
          tag: '$HEROKU_APP_NAME'
  deploy:
    executor: heroku/default
    steps:
      - heroku/install
      - setup_remote_docker
      - push-docker-image
      - release-docker-image
orbs:
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.2.4

version: 2.1
workflows:
  run-jobs:
    jobs:
      - build-and-push
      - deploy:
          requires:
            - build-and-push

