jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME 
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
orbs:
  docker: circleci/docker@1.5.0
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push

