version: 2.1
orbs:
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.2.4
jobs:
  build-and-test:
    executor: docker/default
    steps:
      - publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME 
          tag: 'latest'
  deploy:
    executor: heroku/default
    steps:
      - heroku/install
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Pushing to heroku registry
          command: |
            heroku container:login
            heroku container:push web -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME
workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
