jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME

  deploy:
    executor: heroku/default
    steps:
      - heroku/install
      - checkout
      - setup_remote_docker
      - heroku/deploy-via-git

orbs:
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.2.4

version: 2.1
workflows:
  run-jobs:
    jobs:
      - build-and-push
      - deploy:
          requires:
            - build-and-push

