orbs:
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.2.4

version: 2.1
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          update-description: true
          tag: 'latest'
      - heroku/push-docker-omage:
          app-name: $HEROKU_APP_NAME
