jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
      - docker/push:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME 
          tag: 'latest'
orbs:
  docker: circleci/docker@1.5.0
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push

