orbs:
  heroku: circleci/heroku@1.2.4
  docker: circleci/docker@1.0.0
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          use-docker-credentials-store: true
      - heroku/push-docker-image:
