version: 2.1
orbs:
  docker: circleci/docker@1.5.0

workflows:
  deploy:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
      - run:
         command: heroku container:login 
      - run:
         command: heroku container: release
